name = "naff"
compatibility_date = "2025-04-29"

# Set workers_dev to false for production
workers_dev = false

# Define the build process and assets upload
[build]
command = "npm run build"
upload = { format = "modules", dir = ".svelte-kit/cloudflare" }

# Assets directory for static files
[assets]
directory = ".svelte-kit/cloudflare"

# Add route for both domains (naff.nz and www.naff.nz)
route = ["naff.nz/*", "www.naff.nz/*"]

# Optionally, you can add zone_id if you're managing multiple domains
zone_id = "YOUR_CLOUDFLARE_ZONE_ID"
